name: TEST_Workflow 2

on:
  workflow_run:
    workflows: ["TEST_2"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code 2
        uses: actions/checkout@v2

      - name: Run Tests
        run: echo "Running tests...2222"
